#!/usr/bin/env bash

# Colors taken from tokyonight theme
activec="0xffe87d3e"
blue="0xff7aa2f7"

options=(
  active_color="$activec"
  inactive_color="$blue"
  hidpi=on
  style=round
  width=3.0
  # blacklist="Safari,kitty" # Application blacklist (this is an exampled)
)

borders "${options[@]}"
