# Reference: https://en.wikipedia.org/wiki/ANSI_escape_code
# Inspired by VSCode dark theme (nvim vscode.lua color palette)


# 48;5;n => set background color (8bit)
# 38;5;n => set foreground color (8bit)
# 48;5;n 38;5;n => set bg/set fg
# n =>
# 0->7: standard colors
# 8->15: hight intensity
# >16: 216 colors

[vsdark]
header = 38;5;73                        # FG #5FAFAF
old_path = 38;5;180                     # FG #D7AF87
new_path = 38;5;180                     # FG #D7AF87
hunk_header = 38;5;73                   # FG #5FAFAF
hunk_meta = 38;5;67                     # FG #5F87AF
common_line = 0                         # Reset
old_line = 48;5;52                      # BG #4B1818
new_line = 48;5;22                      # BG #005F00
deleted_text = 48;5;88                  # BG #870000
inserted_text = 38;5;253 48;5;65        # FG #E4E4E4  BG #5F875F
replaced_old_text = 48;5;88              # BG #870000
replaced_new_text = 38;5;253 48;5;65    # FG #E4E4E4  BG #5F875F
old_line_number = 38;5;240              # FG #5A5A5A
new_line_number = 38;5;240              # FG #5A5A5A
file_separator = 38;5;240               # FG #5A5A5A
wrap_marker = 38;5;97                   # FG #875faf
