#!/bin/bash

# General Icons
BAR_ICON_LOADING=󰝲
BAR_ICON_APPLE=
BAR_ICON_PREFERENCES=󰢻
BAR_ICON_ACTIVITY=
BAR_ICON_LOCK=
BAR_ICON_BELL=󰂚
BAR_ICON_BELL_DOT=󱅫

# Battery Icons
BAR_ICON_BATTERY_100=󰁹
BAR_ICON_BATTERY_75=󰂀
BAR_ICON_BATTERY_50=󰁾
BAR_ICON_BATTERY_25=󰁼
BAR_ICON_BATTERY_0=󰂎
BAR_ICON_BATTERY_CHARGING=󱊦


# Aeropace Icons
