[mgr]

prepend_keymap = [
  { on = "k", run = "arrow -1", desc = "Previous file" },
  { on = "j", run = "arrow 1", desc = "Next file" },
  { on = ["g", "c"], run = "plugin git-files", desc="Show Git file changes"}
]

